FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app
# Copy csproj and restore as distinct layers
COPY ./LinnworksTest ./
RUN dotnet restore
# Setup NodeJs
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs

RUN dotnet publish -c Release -o out

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]
